spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;DatabaseName=义工表
    username: dtl
    password: 123456
    # 配置监控统计拦截的filter，去掉后监控界面sql将无法统计，“wall”用于防火墙
    filters: stat,wall,log4j
    dbcp2:
    #获取连接时候验证，会影响性能
      test-on-borrow: false
      #连接池空闲连接的有效时间  3000秒
      min-evictable-idle-time-millis: 3600000
      #指定连接池等待连接返回的最大等待时间，毫秒单位.
      max-wait-millis: 20000
      #验证连接的有效性
      test-while-idle: true
      #空闲连接回收的时间间隔，与test-while-idle一起使用，设置5分钟
      time-between-eviction-runs-millis: 300000
      min-idle: 10
      initial-size: 10
      max-idle: 100
      max-total: 100




    #最大活跃数
    #初始化数量
    #最大连接等待超时时间
    #打开PSCahe,并且指定每个连接PSCache的大小
  mvc:
    static-path-pattern: /static/**
    #将static下的所有文件夹及相关子文件夹都添加进扫描路径，那么修改之后重启项目就可以对static下的静态资源进行分类而且访问的时候不会出现404了


  jpa:
    database: sql_server
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
server:
  port: 8080
  tomcat:
    max-threads: 1000
